--- !ruby/object:Jumpstart::Configuration
application_name: Caliber
business_name: Caliber, Inc.
domain: example.com
support_email: support@caliberapp.co
default_from_email: Jumpstart <support@example.com>
business_address: ''
background_job_processor: sidekiq
email_provider: ''
personal_accounts: true
livereload: true
register_with_account: false
